import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./pico.classless.indigo.min.css";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StyledComponentsRegistry>
					<Header />
					<main className="container">{children}</main>
					<Footer />
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
